mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from shop.views import products_list, product_detail, home, contactView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^products/', products_list, name='products'),
    url(r'^contact/', contactView, name='contact'),
    url(r'^(?P<product_id>\d+)/$', product_detail, name='product'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/shop/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField("название", max_length=50)
    price = models.IntegerField("цена")
    description = models.TextField("описание")
    photo = models.ImageField("фотография", upload_to="shop/photos", default="", blank=True)

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товара"

    def __str__(self):
        return self.name

mysite/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from django import forms
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError


def home(request):
    products = Product.objects.all()
    return render(request, "products/home.html", {"products": products})


def products_list(request):
    products = Product.objects.all()
    return render(request, "products/products_list.html", {"products": products})


def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, "products/product_detail.html", {"product": product})


class ContactForm(forms.Form):
    subject = forms.CharField(max_length = 100)
    sender = forms.EmailField()
    message = forms.CharField()
    copy = forms.BooleanField(required = False)


def contactView(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        #Если форма заполнена корректно, сохраняем все введённые пользователем значения
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']

            recipients = ['ВАШ_EMAIL_ДЛЯ_ПОЛУЧЕНИЯ_СООБЩЕНИЯ']
            #Если пользователь захотел получить копию себе, добавляем его в список получателей
            if copy:
                recipients.append(sender)
            try:
                send_mail(subject, message, 'ВАШ_EMAIL_ДЛЯ_ОТПРАВКИ_СООБЩЕНИЯ', recipients)
            except BadHeaderError: #Защита от уязвимости
                return HttpResponse('Invalid header found')
            #Переходим на другую страницу, если сообщение отправлено
            return render(request, 'products/thanks.html')
    else:
        #Заполняем форму
        form = ContactForm()
    #Отправляем форму на страницу
    return render(request, 'products/contact.html', {'form': form})

mysite/shop/templates/products/contact.html
{% extends "index.html" %}

{% block application %}
    <form action="/contact/" method="post">{% csrf_token %}
    {{ form.non_field_errors }}
    <div>
      <label for="id_subject">Тема:</label>
      {{ form.subject.errors }}
      {{ form.subject }}
    </div>
    <div>
      <label for="id_sender">E-mail:</label>
      {{ form.sender.errors }}
      {{ form.sender }}
    </div>
    <div>
      <label for="id_message">Сообщение:</label>
      {{ form.message.errors }}
      {{ form.message }}
    </div>
    <div>
      {{ form.copy.errors }}
      <label for="id_copy">Отправить копию себе {{ form.copy }}</label>
    </div>
    <input type="submit" value="Отправить"/>
</form>

<script src="http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU" type="text/javascript"></script>
<script type="text/javascript">
        // Как только будет загружен API и готов DOM, выполняем инициализацию
        ymaps.ready(init);
 
        function init () {
            // Создание экземпляра карты и его привязка к контейнеру с
            // заданным id ("map")
            var myMap = new ymaps.Map('map', {
                    // При инициализации карты, обязательно нужно указать
                    // ее центр и коэффициент масштабирования
                    center: [56.326944, 44.0075], // Нижний Новгород
                    zoom: 13
                });
        }
    </script>

    <div id="map" style="width:600px; height:400px"></div>

{% endblock %}

mysite/shop/templates/products/home.html
{% extends "index.html" %}

{% block application %}
<li>
    <a href="{% url 'products' %}">Каталог</a>
    {% for product in products %}
    <a href="{% url 'product' product_id=product.id %}">{{ product.id }}</a>
    {% endfor %}
</li>
<li>
    <a href="{% url 'contact' %}">Форма обратной связи</a>
</li>

<table align="center" width="600" bgcolor="#ffcc00">
   <tr>
    {% for product in products %}
        <td> <img src="{{ product.photo.url }}" alt="{{ product.name }}"> </td>
    {% endfor %}
   </tr>
</table>

{% endblock %}

mysite/shop/templates/products/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Пример карты с использованием JavaScript API Яндекс.Карт 2.0</title>
<!-- Подключаем API  карт 2.x  -->
<script src="http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU" type="text/javascript"></script>
<script type="text/javascript">
        // Как только будет загружен API и готов DOM, выполняем инициализацию
        ymaps.ready(init);
 
        function init () {
            // Создание экземпляра карты и его привязка к контейнеру с
            // заданным id ("map")
            var myMap = new ymaps.Map('map', {
                    // При инициализации карты, обязательно нужно указать
                    // ее центр и коэффициент масштабирования
                    center: [56.326944, 44.0075], // Нижний Новгород
                    zoom: 13
                });
        }
    </script>
</head>
 
<body>
<div id="map" style="width:600px; height:400px"></div>
</body>
</html>

mysite/shop/templates/products/product_detail.html
{% extends "index.html" %}

{% block application %}
    <div>
        <h2>{{ product.name }}</h2>
        {% if product.photo %}
            <img src="{{ product.photo.url }}" alt="{{ product.name }}">
        {% endif %}
        <div>{{ product.price }}</div>
        <div>{{ product.description }}</div>
    </div>
{% endblock %}

mysite/shop/templates/products/products_list.html
{% extends "index.html" %}

{% block application %}

{% for product in products %}
<div>
    <h2>{{ product.name }}</h2>
    {% if product.photo %}
        <img src="{{ product.photo.url }}" alt="{{ product.name }}">
    {% endif %}
    <div>{{ product.price }}</div>
    <div>{{ product.description }}</div>
</div>
{% endfor %}

{% endblock %}

mysite/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>

{% block application %}

{% endblock %}


</body>
</html>